### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kbaba1001** [kbaba1001/web_diary#1]
- [x] 自動デプロイ ( middleman-deploy )
- [x] Twitter や Facebook のボタンつけたい
- [x] コメント機能 ( middleman-disqus )
- [ ] tag、calendarページのデザイン
- [ ] ページネーションのデザイン
